package com.jihedailabs.devtools.idempotentscaffolder;

import java.util.List;

/**
 * Produces the two files behind the idempotent-consumer pattern: the migration that creates the
 * processed-events table, and the repository that writes to it.
 *
 * <p>Modelled on the hand-written implementation in
 * <a href="https://github.com/jihedbfr-art/bpmn-provisioning-patterns">bpmn-provisioning-patterns</a>
 * ({@code ProcessedEventRepository} + {@code V1__outbox_and_processed_events.sql}), which is where
 * the comments in the generated code come from — each one marks something that actually went
 * wrong there before it was written down.
 */
public final class Scaffolder {

    /** Width the column names are padded to, so the generated DDL stays readable. */
    private static final int COLUMN_NAME_WIDTH = 15;

    private Scaffolder() {
    }

    public static List<GeneratedFile> generate(ScaffoldOptions options) {
        return List.of(
                new GeneratedFile(options.migrationPath(), migration(options)),
                new GeneratedFile(options.repositoryPath(), repository(options)));
    }

    private static String migration(ScaffoldOptions options) {
        return """
                -- Generated by kafka-idempotent-consumer-scaffolder ({{DIALECT_NAME}}).
                --
                -- Identifiers are unquoted on purpose. Quoting them ("{{TABLE}}") makes the name
                -- case-sensitive, and H2 folds unquoted names to UPPERCASE where PostgreSQL folds
                -- them to lowercase — a table created quoted on one engine is then unreachable by
                -- the same query on the other. Leaving every identifier unquoted and lowercase is
                -- the only spelling that means the same thing on both.

                CREATE TABLE {{TABLE}} (
                    {{EVENT_ID_PAD}}VARCHAR(64)  NOT NULL,
                    topic          VARCHAR(128) NOT NULL,
                    aggregate_id   VARCHAR(64)  NOT NULL,
                    processed_at   TIMESTAMP    NOT NULL,
                    CONSTRAINT pk_{{TABLE}} PRIMARY KEY ({{EVENT_ID}})
                );

                -- The primary key is not decoration: it is the entire idempotency mechanism. The
                -- repository never checks whether a row exists, it just inserts and lets the
                -- database reject the second writer. Drop this constraint and two consumers
                -- redelivering the same event will both believe they are the first.

                -- {{TABLE}} grows for as long as the topic does. This index is what makes the
                -- retention delete cheap once it stops being a small table.
                CREATE INDEX idx_{{TABLE}}_processed_at ON {{TABLE}} (processed_at);
                """
                .replace("{{DIALECT_NAME}}", options.dialect().displayName())
                .replace("{{TABLE}}", options.table())
                // Padded so the column list stays aligned whatever the event id column is called.
                .replace("{{EVENT_ID_PAD}}", padded(options.eventIdColumn()))
                .replace("{{EVENT_ID}}", options.eventIdColumn());
    }

    private static String padded(String identifier) {
        return identifier.length() >= COLUMN_NAME_WIDTH
                ? identifier + " "
                : identifier + " ".repeat(COLUMN_NAME_WIDTH - identifier.length());
    }

    private static String repository(ScaffoldOptions options) {
        return """
                package {{PACKAGE}};

                import org.springframework.dao.DuplicateKeyException;
                import org.springframework.jdbc.core.JdbcTemplate;
                import org.springframework.stereotype.Repository;

                import java.sql.Timestamp;
                import java.time.Instant;

                /**
                 * Idempotency guard for a Kafka consumer, backed by the {@code {{TABLE}}} table.
                 *
                 * <p>Generated by kafka-idempotent-consumer-scaffolder for {{DIALECT_NAME}}.
                 *
                 * <p>Two properties this class depends on, both easy to lose in a later refactor:
                 *
                 * <ol>
                 *   <li><b>Call {@link #markProcessed} inside the same transaction as the business
                 *       work.</b> If the insert commits on its own and the handler then fails, the
                 *       event is marked processed and its effect never happened — the redelivery
                 *       Kafka is about to send will be skipped. Annotating the listener
                 *       {@code @Transactional} is what makes the guard and the work land or roll
                 *       back together.</li>
                 *   <li><b>Never SELECT before INSERT.</b> Checking for the row first and inserting
                 *       if absent looks equivalent and is not: two consumers in the same partition
                 *       rebalance window can both read "absent" before either writes. The unique
                 *       constraint is the only check that cannot be raced.</li>
                 * </ol>
                 */
                @Repository
                public class {{CLASS}} {

                    private static final String INSERT_SQL =
                            "{{INSERT_SQL}}";

                    private static final String PURGE_SQL =
                            "DELETE FROM {{TABLE}} WHERE processed_at < ?";

                    private final JdbcTemplate jdbc;

                    public {{CLASS}}(JdbcTemplate jdbc) {
                        this.jdbc = jdbc;
                    }

                    /**
                     * Claims this event id for the current transaction.
                     *
                     * @return {@code true} when the event has not been handled before and the caller
                     *         should process it; {@code false} when it is a redelivery to skip.
                     */
                    public boolean markProcessed(String eventId, String topic, String aggregateId) {
                        try {
                            int rows = jdbc.update(INSERT_SQL, eventId, topic, aggregateId,
                                    Timestamp.from(Instant.now()));
                            return rows > 0;
                        } catch (DuplicateKeyException alreadyProcessed) {
                            // Engines without ON CONFLICT (H2 outside PostgreSQL compatibility mode
                            // among them) report the duplicate by throwing instead of returning 0.
                            // Both branches are kept even when the target dialect only uses one, so
                            // that testing on H2 and running on PostgreSQL behaves identically.
                            return false;
                        }
                    }

                    /**
                     * Deletes rows processed before {@code cutoff}, and returns how many went.
                     *
                     * <p>Nothing calls this for you. The table only ever grows otherwise, and the
                     * safe cutoff is a business decision: it must stay well beyond the broker's
                     * retention, or a message replayed from an offset older than the purge will be
                     * treated as new.
                     */
                    public int purgeProcessedBefore(Instant cutoff) {
                        return jdbc.update(PURGE_SQL, Timestamp.from(cutoff));
                    }
                }
                """
                .replace("{{PACKAGE}}", options.packageName())
                .replace("{{CLASS}}", options.className())
                .replace("{{TABLE}}", options.table())
                .replace("{{DIALECT_NAME}}", options.dialect().displayName())
                .replace("{{INSERT_SQL}}", options.dialect()
                        .insertStatement(options.table(), options.eventIdColumn()));
    }
}
